### ISSUE TITLE
Question: 32-bit architecture

### ISSUE THREAD

**Issue by fabianmendes** [Itai-Nelken/Ubuntu-on-rpi-fixes#2]
Hi, Itai! Excuse me, does the instruction about "Install box86" work for RPi OS 64-bit (aarch64) to use all 32-bit apps in the same system??

Thanks!

**Comment by Itai-Nelken** [comment]
I don't know, I never tried it.
but you are welcome to try and report any errors if there are.

**Comment by Itai-Nelken** [comment]
@fabianmendes did you try it?

**Comment by fabianmendes** [comment]
> @fabianmendes did you try it? and if yes did it work?

No, man. Also, I have a toxic relationship with the 64-bit RPi OS versions :L 
I am not sure when I will give it a try.. especially because I'm always using my RPi 32-bit OS setup

**Comment by Itai-Nelken** [comment]
I'm closing this issue, @fabianmendes feel free to reply if you need any more help and I'll reopen it.
you can also use the discussions tab next time.

**Comment by fabianmendes** [comment]
All right thanks!
